name: Java CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'
          cache: 'maven'

      - name: Setup Maven
        uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: '[{"id": "github", "username": "dummy", "password": "${MAVEN_REPO_SECRET}"}]'
          githubServer: false

      - name: Build with Maven
        run: mvn -U --batch-mode test
        env:
          MAVEN_REPO_SECRET: ${{ secrets.MAVEN_REPO_SECRET }}
